---
resources:
  - name: resource
    type: git
    source:
      uri: https://github.com/starkandwayne/concourse-tutorial.git
      branch: master

  - name: source-code
    type: git
    webhook_token:((github.webhook))
    source:
	branch: master
	uri: https://github.com/PoojaJain0294/concourseDemo.git
	username: ((github.username))
	password: ((gitHub.paasword))

groups:
 - name: group 1
   jobs:
   - job-pass-files

 - name: group 2
   jobs:
   - hello-world

jobs:
  - name: job-pass-files
    public: true
    plan:
      - get: resource-tutorial
      - task: create-some-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}

          inputs:
            - name: resource-tutorial
          outputs:
            - name: some-files

          run:
            path: resource-tutorial/tutorials/basic/task-outputs-to-inputs/create_some_files.sh

      - task: show-some-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}

          inputs:
            - name: resource-tutorial
            - name: some-files

          run:
            path: resource-tutorial/tutorials/basic/task-outputs-to-inputs/show_files.sh

  - name: hello-world
    plan:
      - in_parrallel:
      	- get: resource-tutorial
	- get: source-code
	  trigger: true
	  passed: [job-pass-files]

      	- task: print hello
          config:
            platform: linux
            image_resource:
             type: docker-image
             source: {repository: busybox}

          inputs:
            - name: source-code

          run:
            path: echo
	    args: ["Hello!!"]
